"""
scripts/validate_no_internal_leaks.py
CI/CD Guard: Valida que la documentación pública no contenga acrónimos internos (GP-xxx),
nombres de módulos de andamiaje, divulgaciones de datos dummy o marcas de IA.
"""

from pathlib import Path
import re
import sys

PROHIBITED_LEAK_PATTERNS = [
    (r"GP-\d{3,6}", "Internal Ghost Project ID (GP-xxx)"),
    (r"Ghost\s+Architect", "Internal system moniker ('Ghost Architect')"),
    (r"anti_monotony_memory", "Internal module reference ('anti_monotony_memory')"),
    (r"synthetic\s+dataset", "Synthetic data disclosure ('synthetic dataset')"),
    (r"dummy\s+data", "Dummy data disclosure ('dummy data')"),
    (r"generated\s+by\s+(?:ai|gpt|claude|gemini|antigravity)", "AI provenance disclosure ('generated by...')"),
]

TARGET_DOCS = ["README.md", "00_SPEC.md", "docs/overview.md", "docs/architecture.md"]


def main():
    root = Path(".").resolve()
    files_to_check = []

    for doc_name in TARGET_DOCS:
        p = root / doc_name
        if p.exists():
            files_to_check.append(p)

    for md in root.glob("*.md"):
        if md not in files_to_check:
            files_to_check.append(md)

    if not files_to_check:
        print("[Leaks Guard PASS] No se encontraron archivos markdown para auditar.")
        sys.exit(0)

    violations = []
    for file_path in files_to_check:
        try:
            content = file_path.read_text(encoding="utf-8")
        except Exception:
            continue

        lines = content.splitlines()
        for pattern_str, label in PROHIBITED_LEAK_PATTERNS:
            regex = re.compile(pattern_str, re.IGNORECASE)
            for idx, line in enumerate(lines, 1):
                match = regex.search(line)
                if match:
                    violations.append(
                        f"[{file_path.name}:{idx}] {label} matched '{match.group(0)}': {line.strip()[:80]}"
                    )

    if violations:
        print(f"[Leaks Guard FAIL] Se detectaron {len(violations)} fugas internas prohibidas:")
        for v in violations:
            print(f"  - {v}")
        sys.exit(1)

    print("[Leaks Guard PASS] Zero fugas internas detectadas en la documentación.")
    sys.exit(0)


if __name__ == "__main__":
    main()